In [7]:
import numpy as np
arr=np.array([30,60,90,120,150,180,210,240,270,300,330,360])
print("printing array: ",arr)
sin_value=np.sin(arr*np.pi/180)
print("Printing value for sin: ",sin_value)
print("printing value for cos: ", np.cos(arr*np.pi/180))
print("printing value for tan: ", np.cos(arr*np.pi/180))
print("printing cosec value: ", np.arcsin(sin_value))

printing array:  [ 30  60  90 120 150 180 210 240 270 300 330 360]
Printing value for sin:  [ 5.00000000e-01  8.66025404e-01  1.00000000e+00  8.66025404e-01
  5.00000000e-01  1.22464680e-16 -5.00000000e-01 -8.66025404e-01
 -1.00000000e+00 -8.66025404e-01 -5.00000000e-01 -2.44929360e-16]
printing value for cos:  [ 8.66025404e-01  5.00000000e-01  6.12323400e-17 -5.00000000e-01
 -8.66025404e-01 -1.00000000e+00 -8.66025404e-01 -5.00000000e-01
 -1.83697020e-16  5.00000000e-01  8.66025404e-01  1.00000000e+00]
printing value for tan:  [ 8.66025404e-01  5.00000000e-01  6.12323400e-17 -5.00000000e-01
 -8.66025404e-01 -1.00000000e+00 -8.66025404e-01 -5.00000000e-01
 -1.83697020e-16  5.00000000e-01  8.66025404e-01  1.00000000e+00]
printing cosec value:  [ 5.23598776e-01  1.04719755e+00  1.57079633e+00  1.04719755e+00
  5.23598776e-01  1.22464680e-16 -5.23598776e-01 -1.04719755e+00
 -1.57079633e+00 -1.04719755e+00 -5.23598776e-01 -2.44929360e-16]


In [10]:
import numpy as np
arr=np.array([2.034,5.0008,9.089,78.097])
print(np.around(arr,1))

[ 2.   5.   9.1 78.1]


In [11]:
import numpy as np
arr=np.array([2.034,5.0008,9.089,78.097])
print(np.floor(arr))

[ 2.  5.  9. 78.]


In [12]:
import numpy as np
arr=np.array([2.034,5.0008,9.089,78.097])
print(np.ceil(arr))

[ 3.  6. 10. 79.]


# Numpy statistical functions

In [15]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Printing array: ",arr)
print("Printing maximum element in array: ", np.amax(arr))
print("Printing minimum element in array: ", np.amin(arr))
print("Printing maximum element in array as row specified: ", np.amax(arr,1))
print("Printing minimum element in array", np.amin(arr,1))

Printing array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Printing maximum element in array:  9
Printing minimum element in array:  1
Printing maximum element in array as row specified:  [3 6 9]
Printing minimum element in array [1 4 7]
