# creating matrix using array

In [3]:
import numpy as np
arr=np.array([[7,8,2],[4,6,8]])
print(arr)

[[7 8 2]
 [4 6 8]]


In [4]:
import numpy as np
arr=np.array([[7,8,2],[4,6,8]])
print(arr.ndim)

2


In [6]:
import numpy as np
arr=np.array([[7,8,2],[4,6,8]])
print(arr.itemsize)

8


In [7]:
import numpy as np
arr=np.array([[7,8,2],[4,6,8]])
print(arr.dtype)

int64


In [8]:
import numpy as np
arr=np.array([[7,8,2],[4,6,8]])
print(arr.size)

6


In [9]:
import numpy as np
arr=np.array([[7,8,2],[4,6,8]])
print(arr.shape)

(2, 3)


# reshape the array

In [10]:
import numpy as np
arr=np.array([[7,8,2],[4,6,8]])
print(arr.reshape(3,2))

[[7 8]
 [2 4]
 [6 8]]


In [11]:
import numpy as np
arr=np.array([[7,8,2],[4,6,8]])
print(arr.min())
print(arr.max())
print(arr.sum())

2
8
35


In [12]:
    import numpy as np  
    a = np.array([[1,2,30],[10,15,4]])  
    print("The array:",a)  
    print("The maximum elements of columns:",a.max(axis = 0))   
    print("The minimum element of rows",a.min(axis = 1))  
    print("The sum of all rows",a.sum(axis = 1))  



The array: [[ 1  2 30]
 [10 15  4]]
The maximum elements of columns: [10 15 30]
The minimum element of rows [1 4]
The sum of all rows [33 29]


In [17]:
import numpy as np
a=np.array([[1,2,3],[5,7,5]])
b=np.array([[5,7,0],[2,5,8]])
print(np.hstack((a,b)))

[[1 2 3 5 7 0]
 [5 7 5 2 5 8]]


In [21]:
import numpy as np
arr=np.empty((2,3), dtype=int)
print(arr)

[[7 8 2]
 [4 6 8]]


In [23]:
import numpy as np
arr=np.zeros((2,3), dtype= int)
print(arr)

[[0 0 0]
 [0 0 0]]


In [24]:
import numpy as np
arr=np.ones((2,3), dtype= int)
print(arr)

[[1 1 1]
 [1 1 1]]


In [2]:
import numpy as np
l=[1,2,3,4,5,6,7]
print(np.asarray(l))

[1 2 3 4 5 6 7]


# NumPy Array Iteration

In [5]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[4,5,7]])
print("Printing Array....")
print(arr)
print("Printing Transpose of array...")
at=arr.T
print(at)
print("Printing iteration of array")
for x in np.nditer(arr):
    print(x,end="")

Printing Array....
[[1 2 3]
 [4 5 6]
 [4 5 7]]
Printing Transpose of array...
[[1 4 4]
 [2 5 5]
 [3 6 7]]
Printing iteration of array
123456457

In [7]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("now reshaping...")
c=arr.reshape(3,2)
print(c)

[[1 2 3]
 [4 5 6]]
now reshaping...
[[1 2]
 [3 4]
 [5 6]]
